# Generated by Django 4.0 on 2022-11-10 16:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('specialization', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ('-name', '-surname', '-specialization', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('citizen_id', models.CharField(max_length=11)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=12)),
                ('adress', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('-name', '-surname', '-citizen_id', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=5)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patientes.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patientes.patient')),
            ],
            options={
                'ordering': ('-patient', '-doctor', '-date', '-price', '-pk'),
            },
        ),
    ]
