# Generated by Django 4.0 on 2022-11-21 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('patientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('visit_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('name_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patientes.visitcategory'),
        ),
    ]
