# Generated by Django 4.0 on 2022-11-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientes', '0002_visitcategory_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitCategory',
            new_name='Category',
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
            ],
        ),
    ]
