# Generated by Django 4.0 on 2022-12-16 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientes', '0003_rename_visitcategory_category_alter_patient_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='price',
            field=models.CharField(max_length=10),
        ),
    ]
