# Generated by Django 4.0 on 2022-12-16 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patientes', '0004_alter_category_options_alter_visit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('surname',)},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('surname',)},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
