# version: '3.9'
version: '3.7'


services:
  
  web:
    build:
      context: .
    restart: always
   
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py loaddata db_dump.json &&
             python manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    env_file: .env
    volumes: 
      - .:/usr/src/app/dir

    depends_on: 
      - db

    # depends_on: 
    #   db:
    #     condition: service_healthy
    #     restart: true

    links: 
     - db:db
    networks:
      - djangonetwork
    
  db:
    image: postgres:13.3
    # image: postgres:latest

    restart: always

    volumes: 
      - postgres_data:/var/lib/postgresql/data/
    
  
    # healthcheck:
    #   test: [“CMD-SHELL”, “pg_isready”]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10

    env_file: .env 
    networks:
      - djangonetwork
    ports:
      - "5432:5432"
    expose:
    - '5432'


networks:
  djangonetwork:
    driver: bridge

volumes:
  postgres_data:



